### ISSUE TITLE
Information about measurement height over ground.

### ISSUE THREAD

**Issue by magtro** [bczernecki/climate#42]
Hi,

For the wind measurements in the Poland meteo_imgw data set, is there meta-data on the observation height over ground surface? I.e the height of the sensor? To clarify, I am not talking about the elevation above sea level of the measuring station, rather the height of the sensor relative to the ground. 

Regards,
Magnus Tronstad

**Comment by bczernecki** [comment]
Hi Magnus,

There is no official repository providing such a detailed information. According to the WMO standards the recommended height for wind measurements should be 10 m above ground level. 
However, due to changes in the surroundings of stations there have been numerous changes of the wind masts over years, and there are many stations that have higher masts than the suggested 10 metres (it varies on some stations even up to 20-some metres). If you want to get the most up-to-date measurement heights for wind you should contact directly with IMGW-PIB (meteorological network maintenance department).

Best,
Bartek

**Comment by magtro** [comment]
Hi,

Thank you for the information!

Regards,
Magnus
